model_path: /home/luc/Desktop/deploy.prototxt
weights_path: /home/luc/Desktop/model.caffemodel
mean_path: /home/luc/Desktop/mean.binaryproto
label_path: /home/luc/Desktop/labels.txt

image_topic: /camera/rgb/image_raw/downsized
pub_topic: /caffe_ret